name: Forfatter Kaja Nylund
favicon: null
layout_spectrum: 0.8066543948370963
typography_spectrum: 0.9922435020562261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3035631161183119
  lightness: 0.1983898577746004
  saturation: 0.07355917687527835
  rhythmicContrast: 0.9862878790590912
purpose: []
